apiVersion: apps/v1
kind: Deployment
metadata:
  name: tow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tow
  template:
    metadata:
      labels:
        app: tow
    spec:
      containers:
      - image: okteto.dev/tow:latest
        name: tow
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "4cc6f715-6e8a-4858-994f-cd1ea04fec75"
        - name: Vless_Path
          value: "/ss33"
        - name: Vmess_UUID
          value: "4cc6f715-6e8a-4858-994f-cd1ea04fec75"
        - name: Vmess_Path
          value: "/S44"
        - name: Share_Path
          value: "/Share34"
