apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvt
  template:
    metadata:
      labels:
        app: nvt
    spec:
      containers:
      - image: okteto.dev/nvt:latest
        name: nvt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "8731b6fe-48a5-48c2-996d-4379256eaa9b"
        - name: Vless_Path
          value: "/ss33"
        - name: Vmess_UUID
          value: "8731b6fe-48a5-48c2-996d-4379256eaa9b"
        - name: Vmess_Path
          value: "/S44"
        - name: Share_Path
          value: "/Share34"
