apiVersion: apps/v1
kind: Deployment
metadata:
  name: not
spec:
  replicas: 1
  selector:
    matchLabels:
      app: not
  template:
    metadata:
      labels:
        app: not
    spec:
      containers:
      - image: okteto.dev/not:latest
        name: not
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "951eb235-858b-4ca1-bfc1-1bf85635e256"
        - name: Vless_Path
          value: "/ss33"
        - name: Vmess_UUID
          value: "951eb235-858b-4ca1-bfc1-1bf85635e256"
        - name: Vmess_Path
          value: "/S44"
        - name: Share_Path
          value: "/Share34"
