apiVersion: apps/v1
kind: Deployment
metadata:
  name: sod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sod
  template:
    metadata:
      labels:
        app: sod
    spec:
      containers:
      - image: okteto.dev/sod:latest
        name: sod
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "653bbfb0-cdd5-4c17-9ab2-7a2e72822a25"
        - name: Vless_Path
          value: "/ss33"
        - name: Vmess_UUID
          value: "653bbfb0-cdd5-4c17-9ab2-7a2e72822a25"
        - name: Vmess_Path
          value: "/S44"
        - name: Share_Path
          value: "/Share34"
