apiVersion: apps/v1
kind: Deployment
metadata:
  name: sed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sed
  template:
    metadata:
      labels:
        app: sed
    spec:
      containers:
      - image: okteto.dev/sed:latest
        name: sed
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "b60aa692-9289-49f3-89ad-d0bb102e4360"
        - name: Vless_Path
          value: "/ss33"
        - name: Vmess_UUID
          value: "b60aa692-9289-49f3-89ad-d0bb102e4360"
        - name: Vmess_Path
          value: "/S44"
        - name: Share_Path
          value: "/Share34"
