apiVersion: apps/v1
kind: Deployment
metadata:
  name: nut
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nut
  template:
    metadata:
      labels:
        app: nut
    spec:
      containers:
      - image: okteto.dev/nut:latest
        name: nut
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "23a7499e-8099-4224-b8e5-2a0fa3529266"
        - name: Vless_Path
          value: "/ss33"
        - name: Vmess_UUID
          value: "23a7499e-8099-4224-b8e5-2a0fa3529266"
        - name: Vmess_Path
          value: "/S44"
        - name: Share_Path
          value: "/Share34"
