apiVersion: apps/v1
kind: Deployment
metadata:
  name: sot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sot
  template:
    metadata:
      labels:
        app: sot
    spec:
      containers:
      - image: okteto.dev/sot:latest
        name: sot
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "83711137-e820-47d8-88da-4cc9423fa4fa"
        - name: Vless_Path
          value: "/ss33"
        - name: Vmess_UUID
          value: "83711137-e820-47d8-88da-4cc9423fa4fa"
        - name: Vmess_Path
          value: "/S44"
        - name: Share_Path
          value: "/Share34"
