apiVersion: apps/v1
kind: Deployment
metadata:
  name: net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net
  template:
    metadata:
      labels:
        app: net
    spec:
      containers:
      - image: okteto.dev/net:latest
        name: net
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "66b991d4-94f1-40a3-a15a-87f9d89d33c4"
        - name: Vless_Path
          value: "/ss33"
        - name: Vmess_UUID
          value: "66b991d4-94f1-40a3-a15a-87f9d89d33c4"
        - name: Vmess_Path
          value: "/S44"
        - name: Share_Path
          value: "/Share34"
