apiVersion: apps/v1
kind: Deployment
metadata:
  name: nht
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nht
  template:
    metadata:
      labels:
        app: nht
    spec:
      containers:
      - image: okteto.dev/nht:latest
        name: nht
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "b34d3afd-650f-4906-b0d0-ad94ec66edb7"
        - name: Vless_Path
          value: "/ss33"
        - name: Vmess_UUID
          value: "b34d3afd-650f-4906-b0d0-ad94ec66edb7"
        - name: Vmess_Path
          value: "/S44"
        - name: Share_Path
          value: "/Share34"
