apiVersion: apps/v1
kind: Deployment
metadata:
  name: sen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sen
  template:
    metadata:
      labels:
        app: sen
    spec:
      containers:
      - image: okteto.dev/sen:latest
        name: sen
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "8559b4e1-bfc7-489e-ba38-314da5b618bb"
        - name: Vless_Path
          value: "/ss33"
        - name: Vmess_UUID
          value: "8559b4e1-bfc7-489e-ba38-314da5b618bb"
        - name: Vmess_Path
          value: "/S44"
        - name: Share_Path
          value: "/Share34"
