apiVersion: apps/v1
kind: Deployment
metadata:
  name: son
spec:
  replicas: 1
  selector:
    matchLabels:
      app: son
  template:
    metadata:
      labels:
        app: son
    spec:
      containers:
      - image: okteto.dev/son:latest
        name: son
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "icook.tw"
        - name: Vless_UUID
          value: "d04ed7cc-ca90-4406-9ebe-4c328ee3368c"
        - name: Vless_Path
          value: "/ss33"
        - name: Vmess_UUID
          value: "d04ed7cc-ca90-4406-9ebe-4c328ee3368c"
        - name: Vmess_Path
          value: "/S44"
        - name: Share_Path
          value: "/Share34"
